codex: gradle changes to build fenix with isolated splits
app successfully compiles and installs, but crashes (expectedly) at
startup with:

java.lang.RuntimeException: Unable to instantiate application
org.mozilla.fenix.FenixApplication package org.mozilla.fenix.debug:
java.lang.ClassNotFoundException: Didn't find class
"org.mozilla.fenix.FenixApplication"